# Note the naming convention: allthings-lambda-XXXXX
service: allthings-lambda-sls-boilerplate-graphql

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  role: arn:aws:iam::799212276699:role/aws-lambda-basic-execution-role

plugins:
  - serverless-offline

custom:
  # serverless-offline:
  #   babelOptions:
  #     presets: ["env"]

functions:
  graphql:
    handler: dist/handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: get
      - http:
          path: graphql
          method: post
  graphiql:
    handler: dist/handler.graphiqlHandler
    events:
      - http:
          path: graphiql
          method: get
